### ISSUE TITLE
missing Tiller-specific "when" clause for keybindings

### ISSUE THREAD

**Issue by grozan** [chris-kahn/vscode-tiller#8]
Hi

thanks for that extension, it makes switching between files very fast and efficient, I find it great.
One thing which I'd like, though, is to have a dedicated "when" clause I could specify for keybings

The current keybindigs like

```{
  "key": "right",
  "command": "tiller.forward",
  "when": "!editorTextFocus"
}
```

are not suitable for me. Not being in editor focus does not mean I'm in a Tiller window
Other similar extensions, like "File browser" expose a custom `when` clause. 

The keybinding should look something like this instead IMO
```{
  "key": "right",
  "command": "tiller.forward",
  "when": "inTiller"
}
```

I think for the file browser extension it's set here
https://github.com/bodil/vscode-file-browser/blob/f9b61efa5961f0e06f17ed75fdfd28d9df8b736b/src/extension.ts#L27

could the `inTiller` thing be introduced?
Thanks

**Comment by grozan** [comment]
just realised the "quick browser" extension I was referring to does not set its own context either.
Also realised it's yours as well :-)

could you set a context for your extensions, like File browser does, so that the user can make keybindings which only trigger in this particular context, using a more precise `when` clause, so that they don't interfere with other keybindings?

**Comment by chris-kahn** [comment]
I've published an update now, so there is now an `inTiller` context you can use for keybindings when Tiller is open.
